/* Define GLGFX_GLEXT and include this file */

/* GLX_SGI_video_sync */
GLGFX_GLEXT(PFNGLXGETVIDEOSYNCSGIPROC,             glXGetVideoSyncSGI)
GLGFX_GLEXT(PFNGLXWAITVIDEOSYNCSGIPROC,            glXWaitVideoSyncSGI)
GLGFX_GLEXT(PFNGLXGETREFRESHRATESGIPROC,           glXGetRefreshRateSGI)

/* GL_ARB_vertex_buffer_object & GL_ARB_pixel_buffer_object */
GLGFX_GLEXT(PFNGLBINDBUFFERARBPROC,                glBindBufferARB)
GLGFX_GLEXT(PFNGLDELETEBUFFERSARBPROC,             glDeleteBuffersARB)
GLGFX_GLEXT(PFNGLGENBUFFERSARBPROC,                glGenBuffersARB)
GLGFX_GLEXT(PFNGLISBUFFERARBPROC,                  glIsBufferARB)
GLGFX_GLEXT(PFNGLBUFFERDATAARBPROC,                glBufferDataARB)
GLGFX_GLEXT(PFNGLBUFFERSUBDATAARBPROC,             glBufferSubDataARB)
GLGFX_GLEXT(PFNGLGETBUFFERSUBDATAARBPROC,          glGetBufferSubDataARB)
GLGFX_GLEXT(PFNGLMAPBUFFERARBPROC,                 glMapBufferARB)
GLGFX_GLEXT(PFNGLUNMAPBUFFERARBPROC,               glUnmapBufferARB)
GLGFX_GLEXT(PFNGLGETBUFFERPARAMETERIVARBPROC,      glGetBufferParameterivARB)
GLGFX_GLEXT(PFNGLGETBUFFERPOINTERVARBPROC,         glGetBufferPointervARB)

/* GL_ARB_shader_objects (GL_ARB_shading_language_100) */

/* GL_EXT_framebuffer_object */
GLGFX_GLEXT(PFNGLISRENDERBUFFEREXTPROC,            glIsRenderbufferEXT)
GLGFX_GLEXT(PFNGLBINDRENDERBUFFEREXTPROC,          glBindRenderbufferEXT)
GLGFX_GLEXT(PFNGLDELETERENDERBUFFERSEXTPROC,       glDeleteRenderbuffersEXT)
GLGFX_GLEXT(PFNGLGENRENDERBUFFERSEXTPROC,          glGenRenderbuffersEXT)
GLGFX_GLEXT(PFNGLRENDERBUFFERSTORAGEEXTPROC,       glRenderbufferStorageEXT)
GLGFX_GLEXT(PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC,glGetRenderbufferParameterivEXT)
GLGFX_GLEXT(PFNGLISFRAMEBUFFEREXTPROC,             glIsFramebufferEXT)
GLGFX_GLEXT(PFNGLBINDFRAMEBUFFEREXTPROC,           glBindFramebufferEXT)
GLGFX_GLEXT(PFNGLDELETEFRAMEBUFFERSEXTPROC,        glDeleteFramebuffersEXT)
GLGFX_GLEXT(PFNGLGENFRAMEBUFFERSEXTPROC,           glGenFramebuffersEXT)
GLGFX_GLEXT(PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC,    glCheckFramebufferStatusEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE1DEXTPROC,      glFramebufferTexture1DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE2DEXTPROC,      glFramebufferTexture2DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE3DEXTPROC,      glFramebufferTexture3DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC,   glFramebufferRenderbufferEXT)
GLGFX_GLEXT(PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC,
		   glGetFramebufferAttachmentParameterivEXT)
GLGFX_GLEXT(PFNGLGENERATEMIPMAPEXTPROC,            glGenerateMipmapEXT)
