/* Define GLGFX_GLEXT and include this file */

#ifndef HAVE_GL_GLATI_H
/* Assume X.Org include files if ATI header is present. Now, if
   glATI.h wasn't broken, it might even have compiled. :-( Bloody
   crap! */

/* OpenGL 1.2 */
GLGFX_GLEXT(PFNGLBLENDCOLORPROC,                   glBlendColor)
GLGFX_GLEXT(PFNGLBLENDEQUATIONPROC,		   glBlendEquation)
GLGFX_GLEXT(PFNGLDRAWRANGEELEMENTSPROC,		   glDrawRangeElements)
GLGFX_GLEXT(PFNGLCOLORTABLEPROC,		   glColorTable)
GLGFX_GLEXT(PFNGLCOLORTABLEPARAMETERFVPROC,	   glColorTableParameterfv)
GLGFX_GLEXT(PFNGLCOLORTABLEPARAMETERIVPROC,	   glColorTableParameteriv)
GLGFX_GLEXT(PFNGLCOPYCOLORTABLEPROC,		   glCopyColorTable)
GLGFX_GLEXT(PFNGLGETCOLORTABLEPROC,		   glGetColorTable)
GLGFX_GLEXT(PFNGLGETCOLORTABLEPARAMETERFVPROC,	   glGetColorTableParameterfv)
GLGFX_GLEXT(PFNGLGETCOLORTABLEPARAMETERIVPROC,	   glGetColorTableParameteriv)
GLGFX_GLEXT(PFNGLCOLORSUBTABLEPROC,		   glColorSubTable)
GLGFX_GLEXT(PFNGLCOPYCOLORSUBTABLEPROC,		   glCopyColorSubTable)
GLGFX_GLEXT(PFNGLCONVOLUTIONFILTER1DPROC,	   glConvolutionFilter1D)
GLGFX_GLEXT(PFNGLCONVOLUTIONFILTER2DPROC,	   glConvolutionFilter2D)
GLGFX_GLEXT(PFNGLCONVOLUTIONPARAMETERFPROC,	   glConvolutionParameterf)
GLGFX_GLEXT(PFNGLCONVOLUTIONPARAMETERFVPROC,	   glConvolutionParameterfv)
GLGFX_GLEXT(PFNGLCONVOLUTIONPARAMETERIPROC,	   glConvolutionParameteri)
GLGFX_GLEXT(PFNGLCONVOLUTIONPARAMETERIVPROC,	   glConvolutionParameteriv)
GLGFX_GLEXT(PFNGLCOPYCONVOLUTIONFILTER1DPROC,	   glCopyConvolutionFilter1D)
GLGFX_GLEXT(PFNGLCOPYCONVOLUTIONFILTER2DPROC,	   glCopyConvolutionFilter2D)
GLGFX_GLEXT(PFNGLGETCONVOLUTIONFILTERPROC,	   glGetConvolutionFilter)
GLGFX_GLEXT(PFNGLGETCONVOLUTIONPARAMETERFVPROC,	   glGetConvolutionParameterfv)
GLGFX_GLEXT(PFNGLGETCONVOLUTIONPARAMETERIVPROC,	   glGetConvolutionParameteriv)
GLGFX_GLEXT(PFNGLGETSEPARABLEFILTERPROC,	   glGetSeparableFilter)
GLGFX_GLEXT(PFNGLSEPARABLEFILTER2DPROC,		   glSeparableFilter2D)
GLGFX_GLEXT(PFNGLGETHISTOGRAMPROC,		   glGetHistogram)
GLGFX_GLEXT(PFNGLGETHISTOGRAMPARAMETERFVPROC,	   glGetHistogramParameterfv)
GLGFX_GLEXT(PFNGLGETHISTOGRAMPARAMETERIVPROC,	   glGetHistogramParameteriv)
GLGFX_GLEXT(PFNGLGETMINMAXPROC,			   glGetMinmax)
GLGFX_GLEXT(PFNGLGETMINMAXPARAMETERFVPROC,	   glGetMinmaxParameterfv)
GLGFX_GLEXT(PFNGLGETMINMAXPARAMETERIVPROC,	   glGetMinmaxParameteriv)
GLGFX_GLEXT(PFNGLHISTOGRAMPROC,			   glHistogram)
GLGFX_GLEXT(PFNGLMINMAXPROC,			   glMinmax)
GLGFX_GLEXT(PFNGLRESETHISTOGRAMPROC,		   glResetHistogram)
GLGFX_GLEXT(PFNGLRESETMINMAXPROC,		   glResetMinmax)
GLGFX_GLEXT(PFNGLTEXIMAGE3DPROC,		   glTexImage3D)
GLGFX_GLEXT(PFNGLTEXSUBIMAGE3DPROC,		   glTexSubImage3D)
GLGFX_GLEXT(PFNGLCOPYTEXSUBIMAGE3DPROC,		   glCopyTexSubImage3D)

/* OpenGL 1.3 */
GLGFX_GLEXT(PFNGLACTIVETEXTUREPROC,		   glActiveTexture)
GLGFX_GLEXT(PFNGLCLIENTACTIVETEXTUREPROC,	   glClientActiveTexture)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1DPROC,		   glMultiTexCoord1d)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1DVPROC,		   glMultiTexCoord1dv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1FPROC,		   glMultiTexCoord1f)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1FVPROC,		   glMultiTexCoord1fv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1IPROC,		   glMultiTexCoord1i)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1IVPROC,		   glMultiTexCoord1iv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1SPROC,		   glMultiTexCoord1s)
GLGFX_GLEXT(PFNGLMULTITEXCOORD1SVPROC,		   glMultiTexCoord1sv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2DPROC,		   glMultiTexCoord2d)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2DVPROC,		   glMultiTexCoord2dv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2FPROC,		   glMultiTexCoord2f)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2FVPROC,		   glMultiTexCoord2fv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2IPROC,		   glMultiTexCoord2i)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2IVPROC,		   glMultiTexCoord2iv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2SPROC,		   glMultiTexCoord2s)
GLGFX_GLEXT(PFNGLMULTITEXCOORD2SVPROC,		   glMultiTexCoord2sv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3DPROC,		   glMultiTexCoord3d)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3DVPROC,		   glMultiTexCoord3dv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3FPROC,		   glMultiTexCoord3f)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3FVPROC,		   glMultiTexCoord3fv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3IPROC,		   glMultiTexCoord3i)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3IVPROC,		   glMultiTexCoord3iv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3SPROC,		   glMultiTexCoord3s)
GLGFX_GLEXT(PFNGLMULTITEXCOORD3SVPROC,		   glMultiTexCoord3sv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4DPROC,		   glMultiTexCoord4d)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4DVPROC,		   glMultiTexCoord4dv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4FPROC,		   glMultiTexCoord4f)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4FVPROC,		   glMultiTexCoord4fv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4IPROC,		   glMultiTexCoord4i)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4IVPROC,		   glMultiTexCoord4iv)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4SPROC,		   glMultiTexCoord4s)
GLGFX_GLEXT(PFNGLMULTITEXCOORD4SVPROC,		   glMultiTexCoord4sv)
GLGFX_GLEXT(PFNGLLOADTRANSPOSEMATRIXFPROC,	   glLoadTransposeMatrixf)
GLGFX_GLEXT(PFNGLLOADTRANSPOSEMATRIXDPROC,	   glLoadTransposeMatrixd)
GLGFX_GLEXT(PFNGLMULTTRANSPOSEMATRIXFPROC,	   glMultTransposeMatrixf)
GLGFX_GLEXT(PFNGLMULTTRANSPOSEMATRIXDPROC,	   glMultTransposeMatrixd)
GLGFX_GLEXT(PFNGLSAMPLECOVERAGEPROC,		   glSampleCoverage)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXIMAGE3DPROC,	   glCompressedTexImage3D)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXIMAGE2DPROC,	   glCompressedTexImage2D)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXIMAGE1DPROC,	   glCompressedTexImage1D)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC,	   glCompressedTexSubImage3D)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC,	   glCompressedTexSubImage2D)
GLGFX_GLEXT(PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC,	   glCompressedTexSubImage1D)
GLGFX_GLEXT(PFNGLGETCOMPRESSEDTEXIMAGEPROC,	   glGetCompressedTexImage)

#endif /* HAVE_GL_GLATI_H */

/* OpenGL 1.4 */
GLGFX_GLEXT(PFNGLBLENDFUNCSEPARATEPROC,            glBlendFuncSeparate)
GLGFX_GLEXT(PFNGLFOGCOORDFPROC,			   glFogCoordf)
GLGFX_GLEXT(PFNGLFOGCOORDFVPROC,		   glFogCoordfv)
GLGFX_GLEXT(PFNGLFOGCOORDDPROC,			   glFogCoordd)
GLGFX_GLEXT(PFNGLFOGCOORDDVPROC,		   glFogCoorddv)
GLGFX_GLEXT(PFNGLFOGCOORDPOINTERPROC,		   glFogCoordPointer)
GLGFX_GLEXT(PFNGLMULTIDRAWARRAYSPROC,		   glMultiDrawArrays)
GLGFX_GLEXT(PFNGLMULTIDRAWELEMENTSPROC,		   glMultiDrawElements)
GLGFX_GLEXT(PFNGLPOINTPARAMETERFPROC,		   glPointParameterf)
GLGFX_GLEXT(PFNGLPOINTPARAMETERFVPROC,		   glPointParameterfv)
GLGFX_GLEXT(PFNGLPOINTPARAMETERIPROC,		   glPointParameteri)
GLGFX_GLEXT(PFNGLPOINTPARAMETERIVPROC,		   glPointParameteriv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3BPROC,		   glSecondaryColor3b)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3BVPROC,		   glSecondaryColor3bv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3DPROC,		   glSecondaryColor3d)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3DVPROC,		   glSecondaryColor3dv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3FPROC,		   glSecondaryColor3f)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3FVPROC,		   glSecondaryColor3fv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3IPROC,		   glSecondaryColor3i)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3IVPROC,		   glSecondaryColor3iv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3SPROC,		   glSecondaryColor3s)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3SVPROC,		   glSecondaryColor3sv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3UBPROC,		   glSecondaryColor3ub)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3UBVPROC,	   glSecondaryColor3ubv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3UIPROC,		   glSecondaryColor3ui)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3UIVPROC,	   glSecondaryColor3uiv)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3USPROC,		   glSecondaryColor3us)
GLGFX_GLEXT(PFNGLSECONDARYCOLOR3USVPROC,	   glSecondaryColor3usv)
GLGFX_GLEXT(PFNGLSECONDARYCOLORPOINTERPROC,	   glSecondaryColorPointer)
GLGFX_GLEXT(PFNGLWINDOWPOS2DPROC,		   glWindowPos2d)
GLGFX_GLEXT(PFNGLWINDOWPOS2DVPROC,		   glWindowPos2dv)
GLGFX_GLEXT(PFNGLWINDOWPOS2FPROC,		   glWindowPos2f)
GLGFX_GLEXT(PFNGLWINDOWPOS2FVPROC,		   glWindowPos2fv)
GLGFX_GLEXT(PFNGLWINDOWPOS2IPROC,		   glWindowPos2i)
GLGFX_GLEXT(PFNGLWINDOWPOS2IVPROC,		   glWindowPos2iv)
GLGFX_GLEXT(PFNGLWINDOWPOS2SPROC,		   glWindowPos2s)
GLGFX_GLEXT(PFNGLWINDOWPOS2SVPROC,		   glWindowPos2sv)
GLGFX_GLEXT(PFNGLWINDOWPOS3DPROC,		   glWindowPos3d)
GLGFX_GLEXT(PFNGLWINDOWPOS3DVPROC,		   glWindowPos3dv)
GLGFX_GLEXT(PFNGLWINDOWPOS3FPROC,		   glWindowPos3f)
GLGFX_GLEXT(PFNGLWINDOWPOS3FVPROC,		   glWindowPos3fv)
GLGFX_GLEXT(PFNGLWINDOWPOS3IPROC,		   glWindowPos3i)
GLGFX_GLEXT(PFNGLWINDOWPOS3IVPROC,		   glWindowPos3iv)
GLGFX_GLEXT(PFNGLWINDOWPOS3SPROC,		   glWindowPos3s)
GLGFX_GLEXT(PFNGLWINDOWPOS3SVPROC,		   glWindowPos3sv)

/* OpenGL 1.5 */
GLGFX_GLEXT(PFNGLGENQUERIESPROC,                   glGenQueries)
GLGFX_GLEXT(PFNGLDELETEQUERIESPROC,		   glDeleteQueries)
GLGFX_GLEXT(PFNGLISQUERYPROC,			   glIsQuery)
GLGFX_GLEXT(PFNGLBEGINQUERYPROC,		   glBeginQuery)
GLGFX_GLEXT(PFNGLENDQUERYPROC,			   glEndQuery)
GLGFX_GLEXT(PFNGLGETQUERYIVPROC,		   glGetQueryiv)
GLGFX_GLEXT(PFNGLGETQUERYOBJECTIVPROC,		   glGetQueryObjectiv)
GLGFX_GLEXT(PFNGLGETQUERYOBJECTUIVPROC,		   glGetQueryObjectuiv)
GLGFX_GLEXT(PFNGLBINDBUFFERPROC,		   glBindBuffer)
GLGFX_GLEXT(PFNGLDELETEBUFFERSPROC,		   glDeleteBuffers)
GLGFX_GLEXT(PFNGLGENBUFFERSPROC,		   glGenBuffers)
GLGFX_GLEXT(PFNGLISBUFFERPROC,			   glIsBuffer)
GLGFX_GLEXT(PFNGLBUFFERDATAPROC,		   glBufferData)
GLGFX_GLEXT(PFNGLBUFFERSUBDATAPROC,		   glBufferSubData)
GLGFX_GLEXT(PFNGLGETBUFFERSUBDATAPROC,		   glGetBufferSubData)
GLGFX_GLEXT(PFNGLMAPBUFFERPROC,			   glMapBuffer)
GLGFX_GLEXT(PFNGLUNMAPBUFFERPROC,		   glUnmapBuffer)
GLGFX_GLEXT(PFNGLGETBUFFERPARAMETERIVPROC,	   glGetBufferParameteriv)
GLGFX_GLEXT(PFNGLGETBUFFERPOINTERVPROC,		   glGetBufferPointerv)

/* OpenGL 2.0 */
GLGFX_GLEXT(PFNGLBLENDEQUATIONSEPARATEPROC,	   glBlendEquationSeparate)
GLGFX_GLEXT(PFNGLDRAWBUFFERSPROC,		   glDrawBuffers)
GLGFX_GLEXT(PFNGLSTENCILOPSEPARATEPROC,		   glStencilOpSeparate)
GLGFX_GLEXT(PFNGLSTENCILFUNCSEPARATEPROC,	   glStencilFuncSeparate)
GLGFX_GLEXT(PFNGLSTENCILMASKSEPARATEPROC,	   glStencilMaskSeparate)
GLGFX_GLEXT(PFNGLATTACHSHADERPROC,		   glAttachShader)
GLGFX_GLEXT(PFNGLBINDATTRIBLOCATIONPROC,	   glBindAttribLocation)
GLGFX_GLEXT(PFNGLCOMPILESHADERPROC,		   glCompileShader)
GLGFX_GLEXT(PFNGLCREATEPROGRAMPROC,		   glCreateProgram)
GLGFX_GLEXT(PFNGLCREATESHADERPROC,		   glCreateShader)
GLGFX_GLEXT(PFNGLDELETEPROGRAMPROC,		   glDeleteProgram)
GLGFX_GLEXT(PFNGLDELETESHADERPROC,		   glDeleteShader)
GLGFX_GLEXT(PFNGLDETACHSHADERPROC,		   glDetachShader)
GLGFX_GLEXT(PFNGLDISABLEVERTEXATTRIBARRAYPROC,	   glDisableVertexAttribArray)
GLGFX_GLEXT(PFNGLENABLEVERTEXATTRIBARRAYPROC,	   glEnableVertexAttribArray)
GLGFX_GLEXT(PFNGLGETACTIVEATTRIBPROC,		   glGetActiveAttrib)
GLGFX_GLEXT(PFNGLGETACTIVEUNIFORMPROC,		   glGetActiveUniform)
GLGFX_GLEXT(PFNGLGETATTACHEDSHADERSPROC,	   glGetAttachedShaders)
GLGFX_GLEXT(PFNGLGETATTRIBLOCATIONPROC,		   glGetAttribLocation)
GLGFX_GLEXT(PFNGLGETPROGRAMIVPROC,		   glGetProgramiv)
GLGFX_GLEXT(PFNGLGETPROGRAMINFOLOGPROC,		   glGetProgramInfoLog)
GLGFX_GLEXT(PFNGLGETSHADERIVPROC,		   glGetShaderiv)
GLGFX_GLEXT(PFNGLGETSHADERINFOLOGPROC,		   glGetShaderInfoLog)
GLGFX_GLEXT(PFNGLGETSHADERSOURCEPROC,		   glGetShaderSource)
GLGFX_GLEXT(PFNGLGETUNIFORMLOCATIONPROC,	   glGetUniformLocation)
GLGFX_GLEXT(PFNGLGETUNIFORMFVPROC,		   glGetUniformfv)
GLGFX_GLEXT(PFNGLGETUNIFORMIVPROC,		   glGetUniformiv)
GLGFX_GLEXT(PFNGLGETVERTEXATTRIBDVPROC,		   glGetVertexAttribdv)
GLGFX_GLEXT(PFNGLGETVERTEXATTRIBFVPROC,		   glGetVertexAttribfv)
GLGFX_GLEXT(PFNGLGETVERTEXATTRIBIVPROC,		   glGetVertexAttribiv)
GLGFX_GLEXT(PFNGLGETVERTEXATTRIBPOINTERVPROC,	   glGetVertexAttribPointerv)
GLGFX_GLEXT(PFNGLISPROGRAMPROC,			   glIsProgram)
GLGFX_GLEXT(PFNGLISSHADERPROC,			   glIsShader)
GLGFX_GLEXT(PFNGLLINKPROGRAMPROC,		   glLinkProgram)
GLGFX_GLEXT(PFNGLSHADERSOURCEPROC,		   glShaderSource)
GLGFX_GLEXT(PFNGLUSEPROGRAMPROC,		   glUseProgram)
GLGFX_GLEXT(PFNGLUNIFORM1FPROC,			   glUniform1f)
GLGFX_GLEXT(PFNGLUNIFORM2FPROC,			   glUniform2f)
GLGFX_GLEXT(PFNGLUNIFORM3FPROC,			   glUniform3f)
GLGFX_GLEXT(PFNGLUNIFORM4FPROC,			   glUniform4f)
GLGFX_GLEXT(PFNGLUNIFORM1IPROC,			   glUniform1i)
GLGFX_GLEXT(PFNGLUNIFORM2IPROC,			   glUniform2i)
GLGFX_GLEXT(PFNGLUNIFORM3IPROC,			   glUniform3i)
GLGFX_GLEXT(PFNGLUNIFORM4IPROC,			   glUniform4i)
GLGFX_GLEXT(PFNGLUNIFORM1FVPROC,		   glUniform1fv)
GLGFX_GLEXT(PFNGLUNIFORM2FVPROC,		   glUniform2fv)
GLGFX_GLEXT(PFNGLUNIFORM3FVPROC,		   glUniform3fv)
GLGFX_GLEXT(PFNGLUNIFORM4FVPROC,		   glUniform4fv)
GLGFX_GLEXT(PFNGLUNIFORM1IVPROC,		   glUniform1iv)
GLGFX_GLEXT(PFNGLUNIFORM2IVPROC,		   glUniform2iv)
GLGFX_GLEXT(PFNGLUNIFORM3IVPROC,		   glUniform3iv)
GLGFX_GLEXT(PFNGLUNIFORM4IVPROC,		   glUniform4iv)
GLGFX_GLEXT(PFNGLUNIFORMMATRIX2FVPROC,		   glUniformMatrix2fv)
GLGFX_GLEXT(PFNGLUNIFORMMATRIX3FVPROC,		   glUniformMatrix3fv)
GLGFX_GLEXT(PFNGLUNIFORMMATRIX4FVPROC,		   glUniformMatrix4fv)
GLGFX_GLEXT(PFNGLVALIDATEPROGRAMPROC,		   glValidateProgram)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1DPROC,		   glVertexAttrib1d)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1DVPROC,		   glVertexAttrib1dv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1FPROC,		   glVertexAttrib1f)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1FVPROC,		   glVertexAttrib1fv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1SPROC,		   glVertexAttrib1s)
GLGFX_GLEXT(PFNGLVERTEXATTRIB1SVPROC,		   glVertexAttrib1sv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2DPROC,		   glVertexAttrib2d)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2DVPROC,		   glVertexAttrib2dv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2FPROC,		   glVertexAttrib2f)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2FVPROC,		   glVertexAttrib2fv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2SPROC,		   glVertexAttrib2s)
GLGFX_GLEXT(PFNGLVERTEXATTRIB2SVPROC,		   glVertexAttrib2sv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3DPROC,		   glVertexAttrib3d)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3DVPROC,		   glVertexAttrib3dv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3FPROC,		   glVertexAttrib3f)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3FVPROC,		   glVertexAttrib3fv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3SPROC,		   glVertexAttrib3s)
GLGFX_GLEXT(PFNGLVERTEXATTRIB3SVPROC,		   glVertexAttrib3sv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NBVPROC,		   glVertexAttrib4Nbv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NIVPROC,		   glVertexAttrib4Niv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NSVPROC,		   glVertexAttrib4Nsv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NUBPROC,		   glVertexAttrib4Nub)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NUBVPROC,		   glVertexAttrib4Nubv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NUIVPROC,		   glVertexAttrib4Nuiv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4NUSVPROC,		   glVertexAttrib4Nusv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4BVPROC,		   glVertexAttrib4bv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4DPROC,		   glVertexAttrib4d)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4DVPROC,		   glVertexAttrib4dv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4FPROC,		   glVertexAttrib4f)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4FVPROC,		   glVertexAttrib4fv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4IVPROC,		   glVertexAttrib4iv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4SPROC,		   glVertexAttrib4s)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4SVPROC,		   glVertexAttrib4sv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4UBVPROC,		   glVertexAttrib4ubv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4UIVPROC,		   glVertexAttrib4uiv)
GLGFX_GLEXT(PFNGLVERTEXATTRIB4USVPROC,		   glVertexAttrib4usv)
GLGFX_GLEXT(PFNGLVERTEXATTRIBPOINTERPROC,	   glVertexAttribPointer)

/* GLX_SGI_video_sync */
GLGFX_GLEXT(PFNGLXGETVIDEOSYNCSGIPROC,		   glXGetVideoSyncSGI)
GLGFX_GLEXT(PFNGLXWAITVIDEOSYNCSGIPROC,		   glXWaitVideoSyncSGI)

/* GL_EXT_framebuffer_object */
GLGFX_GLEXT(PFNGLISRENDERBUFFEREXTPROC,		   glIsRenderbufferEXT)
GLGFX_GLEXT(PFNGLBINDRENDERBUFFEREXTPROC,	   glBindRenderbufferEXT)
GLGFX_GLEXT(PFNGLDELETERENDERBUFFERSEXTPROC,	   glDeleteRenderbuffersEXT)
GLGFX_GLEXT(PFNGLGENRENDERBUFFERSEXTPROC,	   glGenRenderbuffersEXT)
GLGFX_GLEXT(PFNGLRENDERBUFFERSTORAGEEXTPROC,	   glRenderbufferStorageEXT)
GLGFX_GLEXT(PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC,glGetRenderbufferParameterivEXT)
GLGFX_GLEXT(PFNGLISFRAMEBUFFEREXTPROC,		   glIsFramebufferEXT)
GLGFX_GLEXT(PFNGLBINDFRAMEBUFFEREXTPROC,	   glBindFramebufferEXT)
GLGFX_GLEXT(PFNGLDELETEFRAMEBUFFERSEXTPROC,	   glDeleteFramebuffersEXT)
GLGFX_GLEXT(PFNGLGENFRAMEBUFFERSEXTPROC,	   glGenFramebuffersEXT)
GLGFX_GLEXT(PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC,	   glCheckFramebufferStatusEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE1DEXTPROC,	   glFramebufferTexture1DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE2DEXTPROC,	   glFramebufferTexture2DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERTEXTURE3DEXTPROC,	   glFramebufferTexture3DEXT)
GLGFX_GLEXT(PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC,   glFramebufferRenderbufferEXT)
GLGFX_GLEXT(PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC, glGetFramebufferAttachmentParameterivEXT)
GLGFX_GLEXT(PFNGLGENERATEMIPMAPEXTPROC,		   glGenerateMipmapEXT)

/* GLX_EXT_texture_from_pixmap */
#ifndef GLX_EXT_texture_from_pixmap
#define GLX_EXT_texture_from_pixmap 1

#define GLX_BIND_TO_TEXTURE_RGB_EXT        0x20D0
#define GLX_BIND_TO_TEXTURE_RGBA_EXT       0x20D1
#define GLX_BIND_TO_MIPMAP_TEXTURE_EXT     0x20D2
#define GLX_BIND_TO_TEXTURE_TARGETS_EXT    0x20D3
#define GLX_Y_INVERTED_EXT                 0x20D4

#define GLX_TEXTURE_FORMAT_EXT             0x20D5
#define GLX_TEXTURE_TARGET_EXT             0x20D6
#define GLX_MIPMAP_TEXTURE_EXT             0x20D7

#define GLX_TEXTURE_FORMAT_NONE_EXT        0x20D8
#define GLX_TEXTURE_FORMAT_RGB_EXT         0x20D9
#define GLX_TEXTURE_FORMAT_RGBA_EXT        0x20DA

#define GLX_TEXTURE_1D_BIT_EXT             0x00000001
#define GLX_TEXTURE_2D_BIT_EXT             0x00000002
#define GLX_TEXTURE_RECTANGLE_BIT_EXT      0x00000004

#define GLX_TEXTURE_1D_EXT                 0x20DB
#define GLX_TEXTURE_2D_EXT                 0x20DC
#define GLX_TEXTURE_RECTANGLE_EXT          0x20DD

#define GLX_FRONT_LEFT_EXT                 0x20DE
#define GLX_FRONT_RIGHT_EXT                0x20DF
#define GLX_BACK_LEFT_EXT                  0x20E0
#define GLX_BACK_RIGHT_EXT                 0x20E1
#define GLX_FRONT_EXT                      GLX_FRONT_LEFT_EXT
#define GLX_BACK_EXT                       GLX_BACK_LEFT_EXT
#define GLX_AUX0_EXT                       0x20E2
#define GLX_AUX1_EXT                       0x20E3 
#define GLX_AUX2_EXT                       0x20E4 
#define GLX_AUX3_EXT                       0x20E5 
#define GLX_AUX4_EXT                       0x20E6 
#define GLX_AUX5_EXT                       0x20E7 
#define GLX_AUX6_EXT                       0x20E8
#define GLX_AUX7_EXT                       0x20E9 
#define GLX_AUX8_EXT                       0x20EA 
#define GLX_AUX9_EXT                       0x20EB

typedef void (*PFNGLXBINDTEXIMAGEEXTPROC) (Display     *display, 
					   GLXDrawable drawable, 
					   int         buffer,
					   const int   *attrib_list);
typedef void (*PFNGLXRELEASETEXIMAGEEXTPROC) (Display     *display, 
					      GLXDrawable drawable, 
					      int         buffer);
#endif /* GLX_EXT_texture_from_pixmap */

GLGFX_GLEXT(PFNGLXBINDTEXIMAGEEXTPROC,             glXBindTexImageEXT)
GLGFX_GLEXT(PFNGLXRELEASETEXIMAGEEXTPROC,          glXReleaseTexImageEXT)
